--- # this is handeler section file 
 
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks: 

    - name: installing httpd on webeservers
      action: yum name=httpd state=present
      notify: start httpd service
  
  handlers:    
    - name: start httpd service
      action: service name=httpd state=started    
