--- # 
- hosts: all
  user: ansible
  become: yes
  coonection: ssh

  tasks:
    - name: installing multiple sfotweres
      yum: name='{{item}}' state=installed
      with_items:
            - httpd
            - java
            - mysql
            - docker
            - git

